# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('uNo', models.AutoField(primary_key=True, serialize=False)),
                ('uId', models.CharField(max_length=30, unique=True)),
                ('uPass', models.CharField(max_length=30)),
                ('uName', models.CharField(max_length=30)),
                ('uEmail', models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
